// Delta
export const DELTA_SET_USER_DATA = 'DELTA_SET_USER_DATA'
export const DELTA_SET_SYNC_TOKEN = 'DELTA_SET_SYNC_TOKEN'
export const DELTA_SET_SYNC_STATUS = 'DELTA_SET_SYNC_STATUS'
export const DELTA_SET_PORTFOLIO = 'DELTA_SET_PORTFOLIO'
export const DELTA_SET_OVERVIEWS = 'DELTA_SET_OVERVIEWS'
export const DELTA_SET_DEVICE_ID = 'DELTA_SET_DEVICE_ID'

// Blockfolio
export const BLOCKFOLIO_SET_TOKEN = 'BLOCKFOLIO_SET_TOKEN'
export const BLOCKFOLIO_SET_PORTFOLIO = 'BLOCKFOLIO_SET_PORTFOLIO'

// Settings
export const SETTINGS_SET_LANGUAGE = 'SETTINGS_SET_LANGUAGE'
export const SETTINGS_SET_THEME = 'SETTINGS_SET_THEME'

// Home (welcome screen)
export const HOME_SHOW_DELTA = 'HOME_SHOW_DELTA'
export const HOME_SHOW_BLOCKFOLIO = 'HOME_SHOW_BLOCKFOLIO'
