// Delta
export const DELTA_SET_USER_DATA = 'DELTA_SET_USER_DATA'
export const DELTA_SET_SYNC_TOKEN = 'DELTA_SET_SYNC_TOKEN'
export const DELTA_SET_SYNC_STATUS = 'DELTA_SET_SYNC_STATUS'
export const DELTA_SET_PORTFOLIO = 'DELTA_SET_PORTFOLIO'
export const DELTA_SET_OVERVIEWS = 'DELTA_SET_OVERVIEWS'
export const DELTA_SET_DEVICE_ID = 'DELTA_SET_DEVICE_ID'

// Blockfolio
export const BLOCKFOLIO_SET_TOKEN = 'BLOCKFOLIO_SET_TOKEN'
export const BLOCKFOLIO_SET_PORTFOLIO = 'BLOCKFOLIO_SET_PORTFOLIO'

// Settings
export const SETTINGS_SET_LANGUAGE = 'SETTINGS_SET_LANGUAGE'
export const SETTINGS_SET_THEME = 'SETTINGS_SET_THEME'
export const SETTINGS_SET_PASSWORD = 'SETTINGS_SET_PASSWORD'
export const SETTINGS_SET_CURRENCY = 'SETTINGS_SET_CURRENCY'
export const SETTINGS_SET_ALT_CURRENCY = 'SETTINGS_SET_ALT_CURRENCY'
export const SETTINGS_SET_DEFAULT_PORTFOLIO = 'SETTINGS_SET_DEFAULT_PORTFOLIO'
export const SETTINGS_SET_INIT = 'SETTINGS_SET_INIT'
export const SETTINGS_LOAD_DONE = 'SETTINGS_LOAD_DONE'
export const SETTINGS_SAVE = 'SETTINGS_SAVE'

// Home (welcome screen)
export const HOME_SHOW_DELTA = 'HOME_SHOW_DELTA'
export const HOME_SHOW_BLOCKFOLIO = 'HOME_SHOW_BLOCKFOLIO'

// Portfolio
export const PORTFOLIO_UPSERT_ENTRY = 'PORTFOLIO_UPSERT_ENTRY'
export const PORTFOLIO_REMOVE_ENTRY = 'PORTFOLIO_REMOVE_ENTRY'
export const PORTFOLIO_UPSERT = 'PORTFOLIO_UPSERT'
export const PORTFOLIO_REMOVE = 'PORTFOLIO_REMOVE'
export const PORTFOLIO_LOAD = 'PORTFOLIO_LOAD'
